((magit-branch nil)
 (magit-commit nil)
 (magit-log
  ("-n256" "--graph" "--color" "--decorate")
  ("-n256" "--color" "--decorate")
  ("-n256" "--decorate")
  ("-n256" "--graph" "--decorate")
  (("--" "hello.py")
   "--graph")
  (("--" "README.md")))
 (magit-merge nil)
 (magit-pull nil)
 (magit-push nil)
 (magit-tbdiff nil))
